# Generated by Django 4.2.7 on 2025-04-15 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_rename_result_json_query_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryfeedback',
            old_name='is_helpful',
            new_name='help_full',
        ),
        migrations.RemoveField(
            model_name='queryfeedback',
            name='query',
        ),
        migrations.AddField(
            model_name='queryfeedback',
            name='nlp_given',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='queryfeedback',
            name='query_sql',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='queryfeedback',
            name='query_user',
            field=models.ForeignKey(default='adavath', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queryfeedback',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='queryfeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
